Feature/fro 26 password reveal
climatepolicyradar/navigator pull request #687
Opened 2022-06-22 10:46 UTC by PatFawbertMills

FRO-26 Adding a password reveal button to the sign in form (and potentially anywhere that uses a password input)

2022-06-22 10:53 UTC, eurolife commented on frontend/src/components/form-inputs/PasswordInput.tsx
> +  type?: string;
Probably don't need the 'type' prop since it will always be a password field in this case.

2022-06-22 10:54 UTC, eurolife commented on frontend/src/components/form-inputs/PasswordInput.tsx
> +          accept={accept}
Not sure we need the 'accept' prop in this case.

2022-06-22 11:09 UTC, eurolife requested changes
Please also update the password/password confirm fields on the auth/activate-account and auth/reset-password pages. You might also want to update it on the account/change-password page as well even though it's currently not being used.

2022-06-22 15:52 UTC, eurolife approved these changes

2022-06-22 15:53 UTC, PatFawbertMills commented
@joel-wright don't merge until I've got my own account to test the pages

2022-06-30 16:16 UTC, joel-wright approved these changes
LGTM

2022-06-30 16:17 UTC, merged