Bak 1063/improve lookups
climatepolicyradar/navigator pull request #737
Opened 2022-08-22 16:37 UTC by THOR300

***Work in Progress PR*** 

Improve design for lookups - BAK/1063

- Added a new backend endpoint "/config"
- Integrated tests for the endpoint (these successfully pass on the make test_backend command)  
- Integrated response_model for the endpoint 
- Updated the frontend to use the new endpoint and render the response data

2022-08-23 10:27 UTC, THOR300 reviewed
**/.idea should ignore in all folders (globbing)

2022-08-23 11:06 UTC, PatFawbertMills commented on frontend/src/pages/search/index.tsx
> +                    document_types: document_types = {},
These collections need to default to empty arrays `[]` as opposed to objects.

2022-08-31 12:46 UTC, PatFawbertMills requested changes
Just need to remove a couple of the query `onSuccess` methods that we don't use

2022-08-31 12:46 UTC, PatFawbertMills commented on frontend/src/hooks/useConfig.ts
> +      onSuccess: (data) => {
Can remove this as it isn't doing anything and we don't need to fire off any side-affects from the query

2022-08-31 12:46 UTC, PatFawbertMills commented on frontend/src/hooks/useLookups.ts
>        onSuccess: (data) => {
Same as `useConfig` we can remove this

2022-08-31 16:02 UTC, PatFawbertMills approved these changes
Looks good nice one 👍

2022-08-31 16:21 UTC, merged